/*CREACION DE LA BD*/
CREATE DATABASE LIBERTADORES CHARACTER SET UTF8MB4 COLLATE UTF8MB4_SPANISH_CI;
/*MUESTRA DE LA BD*/
SHOW DATABASES;
/*USO DE LA BD*/
USE LIBERTADORES;
/*CREACION DE TABLAS DE 1A*/
CREATE TABLE 1A(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
GEOGRAFIA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
INFORMATICA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 1B*/
CREATE TABLE 1B(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
GEOGRAFIA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
INFORMATICA INT(2),
HISTORIA INT(2),
CIVICA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2)
);
/*CR1bEACION DE TABLAS DE 1C*/
CREATE TABLE 1C(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
GEOGRAFIA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
EDUC_FISICA INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
CIVICA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2)
);
/*CREACION DE TABLAS DE 1D*/
CREATE TABLE 1D(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
GEOGRAFIA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
EDUC_FISICA INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
CIVICA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2)
);
/*CREACION DE TABLAS DE 2A*/
CREATE TABLE 2A(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 2B*/
CREATE TABLE 2B(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 2C*/
CREATE TABLE 2C(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 3A*/
CREATE TABLE 3A(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 3B*/
CREATE TABLE 3B(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
/*CREACION DE TABLAS DE 3C*/
CREATE TABLE 3C(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(250),
APELLIDOS VARCHAR(250),
ESPAÑOL INT(2),
MATEMATICAS INT(2),
CIVICA INT(2),
CIENCIAS INT(2),
LENGUA_EXTRANJERA INT(2),
DEPORTE INT(2),
ARTES INT(2),
TECNOLOGIA INT(2),
HISTORIA INT(2),
TUTORIA INT(2),
VIDA_SALUDABLE INT(2),
EQUIDAD_DE_GENERO INT(2)
);
